{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "qt2bcxlu8vy2u"
  },
  "info": {
    "title": "vision-mvp-v1",
    "version": "1.0",
    "summary": "Vision SNS MVP api v1"
  },
  "servers": [
    {
      "url": "https://stoplight.io/mocks/singapore-squad/be-api-spec/100729079",
      "description": "MockServer"
    },
    {
      "url": "http://localhost:8080",
      "description": "local"
    },
    {
      "url": "https://life-api-dev-ddfgcoc74q-du.a.run.app",
      "description": "Dev"
    }
  ],
  "paths": {
    "/v1/auth/signin": {
      "post": {
        "summary": "로그인",
        "operationId": "post-v1-auth-signin",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    },
                    "data": {
                      "type": "string",
                      "description": "발급된 access token"
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data"
                  ]
                },
                "examples": {
                  "이메일 로그인 성공": {
                    "value": {
                      "code": 0,
                      "message": "[DEV] 성공",
                      "data": {
                        "email": "tester01@email.com",
                        "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0ZXIwMUBlbWFpbC5jb20iLCJpYXQiOjE2NjY4NDQ0MDMsImV4cCI6MTY2Njg4NzYwMCwicHJvdmlkZXIiOiJFTUFJTCJ9.igO3288acEbs0_s1ObVhsGcKTx6ROtkB8l-h7EYY1nTUN7TAAqPfS5Cq5OEtux3mNApt6vbEBup6X5pwWJxzpg",
                        "accessTokenExpiresAt": "2022-10-27T16:20:00.945+00:00",
                        "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0ZXIwMUBlbWFpbC5jb20iLCJpYXQiOjE2NjY4NDQ0NDYsImV4cCI6MTY2ODE0MDQ0MCwicHJvdmlkZXIiOiJFTUFJTCJ9.kk3nJR5NEfYloG8OQPLVtJohjE69Hzt7VotthzKUvZABXaigdhIXknrhXpuzDwAiLSMa9WS90un8nOFK7IrhAA",
                        "refreshTokenExpiresAt": "2022-11-11T04:20:40.999+00:00"
                      }
                    }
                  },
                  "카카오 로그인 성공": {
                    "value": {
                      "code": 0,
                      "message": "[DEV] 성공",
                      "data": {
                        "email": "tester01@kakao.com",
                        "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0ZXIwMUBrYWthby5jb20iLCJpYXQiOjE2NjY4NjAxNzgsImV4cCI6MTY2NjkwMzM3OCwicHJvdmlkZXIiOiJFTUFJTCJ9.sao-wXpoMorSt0PmrQeFnDEuXIDcX2qzhG8ZYS8WzKd7QZPWns9OL56lB1fhRskwd55SUupU3xSyKl5xu8E52A",
                        "accessTokenExpiresAt": "2022-10-27T20:42:58.788+00:00",
                        "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0ZXIwMUBrYWthby5jb20iLCJpYXQiOjE2NjY4NjAxNzgsImV4cCI6MTY2ODE1NjE3OCwicHJvdmlkZXIiOiJFTUFJTCJ9.Hu17xw0zOZfBueFXX0XXMVh2hnBAqFZStqW4s4NgrwnYz5STR9AKvD-VED3XSkpuxf-nrCYjzO9RbQdpgAEsOw",
                        "refreshTokenExpiresAt": "2022-11-11T08:42:58.789+00:00"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "error": {
                      "type": "string"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    }
                  },
                  "required": [
                    "code",
                    "error",
                    "message"
                  ]
                },
                "examples": {
                  "provider 없이 요청": {
                    "value": {
                      "code": 400,
                      "error": "Bad Request",
                      "message": "provider provider is required"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "로그인 후 토큰을 발급합니다.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "passwd": {
                    "type": "string"
                  },
                  "providerName": {
                    "type": "string",
                    "description": "KAKAO, APPLE, EMAIL"
                  }
                },
                "required": [
                  "email",
                  "passwd",
                  "providerName"
                ]
              },
              "examples": {
                "이메일 로그인 요청": {
                  "value": {
                    "email": "tester01@email.com",
                    "passwd": "test1234",
                    "providerName": "EMAIL"
                  }
                },
                "카카오 로그인 요청": {
                  "value": {
                    "code": "ODFrV2ZnSWVZWU1NSkFwUEwwdGhuLUxNdEdCZzFGZ19fdlYzaG5Bb1lmNXU4SFdOQTVNeTFlNnRXWEVyQnpPdVdJVjFtUW9yRE5JQUFBR0VHSkswd1E=",
                    "providerName": "KAKAO"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/tags": {
      "get": {
        "summary": "태그 조회",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    },
                    "data": {
                      "type": "array",
                      "description": "태그 리스트",
                      "items": {
                        "$ref": "#/components/schemas/Tag"
                      }
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data"
                  ]
                },
                "examples": {
                  "태그 리스트 조회 성공": {
                    "value": {
                      "code": 0,
                      "message": "성공",
                      "data": [
                        {
                          "tagId": 1,
                          "tagName": "가지고싶은것"
                        },
                        {
                          "tagId": 2,
                          "tagName": "되고싶은것"
                        },
                        {
                          "tagId": 3,
                          "tagName": "가고싶은곳"
                        },
                        {
                          "tagId": 4,
                          "tagName": "하고싶은것"
                        },
                        {
                          "tagId": 5,
                          "tagName": "일상"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-v1-tags",
        "description": "태그 조회",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ]
      },
      "post": {
        "summary": "태그 등록",
        "operationId": "post-v1-tags",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    },
                    "data": {
                      "type": "integer",
                      "description": "등록된 tag의 id값"
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data"
                  ]
                },
                "examples": {
                  "비전 태그 등록 성공": {
                    "value": {
                      "code": 0,
                      "message": "성공",
                      "data": 90
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "description": "태그 등록",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "tagName": {
                    "type": "string",
                    "description": "태그명"
                  }
                },
                "required": [
                  "tagName"
                ]
              },
              "examples": {
                "비전 태그 등록": {
                  "value": {
                    "tagName": "string"
                  }
                }
              }
            }
          },
          "description": ""
        }
      }
    },
    "/v1/visions": {
      "get": {
        "summary": "비전 목록 조회",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    },
                    "data": {
                      "type": "array",
                      "description": "비전 리스트",
                      "items": {
                        "$ref": "#/components/schemas/Vision"
                      }
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data"
                  ]
                },
                "examples": {
                  "비전 목록 조회 성공": {
                    "value": {
                      "code": 0,
                      "message": "string",
                      "data": [
                        {
                          "visionId": 77,
                          "title": "해외에서 두달 살기",
                          "contents": "하와이, 아이와 함께",
                          "tags": [
                            {
                              "tagId": 1,
                              "tagName": "하고싶은것"
                            },
                            {
                              "tagId": 10,
                              "tagName": "가족"
                            }
                          ],
                          "imgUrl": "https://content.skyscnr.com/m/41acfff761f8ea1a/original/GettyImages-519763361.jpg?resize=1800px:1800px&quality=100",
                          "createAt": "2022-10-19 14:43:25"
                        },
                        {
                          "visionId": 77,
                          "title": "해외에서 백달 살기",
                          "contents": "안드로메다, 월E와 함께",
                          "tags": [
                            {
                              "tagId": 1,
                              "tagName": "갖고 싶은것"
                            },
                            {
                              "tagId": 10,
                              "tagName": "인류애"
                            }
                          ],
                          "imgUrl": "https://content.skyscnr.com/m/41acfff761f8ea1a/original/GettyImages-519763361.jpg?resize=1800px:1800px&quality=100",
                          "createAt": "2022-10-19 14:43:25"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-v1-visions",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ]
      },
      "post": {
        "summary": "비전 등록",
        "operationId": "post-v1-vision",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    },
                    "data": {
                      "type": "integer",
                      "description": "등록된 vision의 id값"
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data"
                  ]
                },
                "examples": {
                  "비전 등록 성공": {
                    "value": {
                      "code": 0,
                      "message": "성공",
                      "data": 101
                    }
                  }
                }
              }
            }
          }
        },
        "description": "비전 등록",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "contents": {
                    "type": "string"
                  },
                  "tagIds": {
                    "type": [
                      "array",
                      "integer"
                    ],
                    "items": {}
                  },
                  "imgUrl": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "비전 등록 ": {
                  "value": {
                    "title": "해외에서 두달 살기",
                    "contents": "하와이, 아이와 함께",
                    "tagIds": [
                      1,
                      10
                    ],
                    "imgUrl": "https://images.unsplash.com/photo-1648612153876-db4fd5ce1a64?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=927&q=80"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/visions/{visionId}": {
      "get": {
        "summary": "비전 단건 조회",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Vision"
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data"
                  ]
                },
                "examples": {
                  "비전 조회 성공": {
                    "value": {
                      "code": 0,
                      "message": "성공",
                      "data": {
                        "visionId": 77,
                        "title": "해외에서 두달 살기",
                        "contents": "하와이, 아이와 함께",
                        "tags": [
                          {
                            "tagId": 1,
                            "tagName": "하고싶은것"
                          },
                          {
                            "tagId": 10,
                            "tagName": "가족"
                          }
                        ],
                        "imgUrl": "https://content.skyscnr.com/m/41acfff761f8ea1a/original/GettyImages-519763361.jpg?resize=1800px:1800px&quality=100",
                        "createAt": "2022-10-19 14:43:25"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-v1-vision",
        "description": "비전 상세 페이지",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ]
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "visionId",
          "in": "path",
          "required": true,
          "description": "비전의 id값"
        }
      ]
    },
    "/healthcheck": {
      "get": {
        "summary": "\bHealth Check",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    }
                  }
                },
                "examples": {
                  "성공": {
                    "value": {
                      "code": 0,
                      "message": "성공"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-healthcheck",
        "description": "Health Check용"
      }
    },
    "/v1/tags/{tagId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "tagId",
          "in": "path",
          "required": true,
          "description": "삭제할 tag id값"
        }
      ],
      "delete": {
        "summary": "",
        "operationId": "delete-v1-tags-tagId",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    }
                  }
                },
                "examples": {
                  "삭제 성공": {
                    "value": {
                      "code": 0,
                      "message": "성공"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "태그 삭제",
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ]
      }
    },
    "/v1/files": {
      "post": {
        "summary": "",
        "operationId": "post-v1-files",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    },
                    "data": {
                      "type": "string",
                      "description": "업로드된 파일 URL"
                    }
                  }
                },
                "examples": {
                  "성공": {
                    "value": {
                      "code": 0,
                      "message": "성공"
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ]
      }
    },
    "/v1/files/urls": {
      "post": {
        "summary": "",
        "operationId": "post-v1-files",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "$ref": "#/components/schemas/ResponseCode"
                    },
                    "message": {
                      "$ref": "#/components/schemas/ResponseMessage"
                    },
                    "data": {
                      "type": "string",
                      "description": "업로드된 파일 URL"
                    }
                  }
                },
                "examples": {
                  "성공": {
                    "value": {
                      "code": 0,
                      "message": "성공"
                    }
                  }
                }
              }
            }
          },
          "": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "url": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          }
        ]
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "User": {
        "title": "User",
        "type": "object",
        "description": "",
        "examples": [
          {
            "id": 142,
            "firstName": "Alice",
            "lastName": "Smith",
            "email": "alice.smith@gmail.com",
            "dateOfBirth": "1997-10-31",
            "emailVerified": true,
            "signUpDate": "2019-08-24"
          }
        ],
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for the given user."
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date",
            "example": "1997-10-31"
          },
          "emailVerified": {
            "type": "boolean",
            "description": "Set to true if the user's email has been verified."
          },
          "createDate": {
            "type": "string",
            "format": "date",
            "description": "The date that the user was created."
          }
        },
        "required": [
          "id",
          "firstName",
          "lastName",
          "email",
          "emailVerified"
        ]
      },
      "ResponseCode": {
        "title": "ResponseCode",
        "x-stoplight": {
          "id": "594lp3cglk3lh"
        },
        "type": "integer",
        "description": "응답 코드\n\n0 (성공),\n9999 (알수없는 에러)"
      },
      "ResponseMessage": {
        "title": "ResponseMessage",
        "x-stoplight": {
          "id": "vmsrg3uyrskuc"
        },
        "type": "string",
        "description": "응답 코드에 대한 설명 (회원에게 노출용 아님)\n\ncode(0) = 성공, \ncode(9999) = 알 수 없는 에러,\n..."
      },
      "Tag": {
        "title": "Tag",
        "x-stoplight": {
          "id": "gp3odcej1yr4k"
        },
        "type": "object",
        "description": "태그 리스트",
        "properties": {
          "tagId": {
            "type": "integer"
          },
          "tagName": {
            "type": "string"
          }
        }
      },
      "Vision": {
        "title": "Vision",
        "x-stoplight": {
          "id": "rpvuv71tertxt"
        },
        "type": "object",
        "examples": [
          {
            "visionId": 77,
            "title": "해외에서 두달 살기",
            "contents": "하와이, 아이와 함께",
            "tags": [
              {
                "tagId": 1,
                "tagName": "하고싶은것"
              },
              {
                "tagId": 10,
                "tagName": "가족"
              }
            ],
            "imgUrl": "https://images.unsplash.com/photo-1648612153876-db4fd5ce1a64?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=927&q=80",
            "createAt": "2022-10-19 14:43:25"
          }
        ],
        "properties": {
          "visionId": {
            "$ref": "#/components/schemas/VisionId"
          },
          "title": {
            "type": "string",
            "description": "비전 제목"
          },
          "contents": {
            "type": "string",
            "description": "비전 상세 설명"
          },
          "tags": {
            "description": "등록된 태그들",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tag"
            }
          },
          "imgUrl": {
            "type": "string",
            "description": "이미지 URL"
          },
          "createTime": {
            "$ref": "#/components/schemas/Time"
          }
        },
        "required": [
          "visionId",
          "imgUrl",
          "createTime"
        ]
      },
      "VisionId": {
        "title": "VisionId",
        "x-stoplight": {
          "id": "ymo0953q1pdgm"
        },
        "type": "integer",
        "description": "비전의 id값",
        "examples": [
          77
        ]
      },
      "Time": {
        "title": "Time",
        "x-stoplight": {
          "id": "9ovpilriqw3o2"
        },
        "type": "string",
        "description": "시간 (YYYY-mm-dd HH:mm:ss)",
        "examples": [
          "2022-12-31 13:00:00"
        ]
      },
      "Date": {
        "title": "Date",
        "x-stoplight": {
          "id": "ojprffqrezdvs"
        },
        "type": "string",
        "description": "날짜 (YYYY-mm-dd)",
        "examples": [
          "2022-12-31"
        ]
      }
    },
    "securitySchemes": {},
    "parameters": {
      "Authorization": {
        "name": "Authorization",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "Bearer MQ=="
        },
        "description": "Bearer accessToken",
        "required": true
      },
      "visionId": {
        "name": "visionId",
        "in": "query",
        "required": true,
        "schema": {
          "type": "integer"
        },
        "description": "비전의 id값"
      }
    }
  }
}